### ISSUE TITLE
Запуск на кастомном порте

### ISSUE THREAD

**Issue by Astromis** [impworks/bonsai#240]
Привет.

Спасибо за приложение, лучшее, что я видел.

Хотел попросить объяснить, как можно запустить его на другом порте. Сам пробовал гуглить, но что-то не получилось.

**Comment by impworks** [comment]
Добрый день! Спасибо за отзыв.

Если вам нужен кастомный порт, то проще всего будет поднять сервис без traefik (т.е. вырезать все его упоминания из `docker-compose.yml`) и настроить маппинг внутреннего порта 80 на тот порт снаружи, который вы хотите. Это также можно сделать в docker-compose или в UI менеджера контейнеров, которым вы пользуетесь.

У меня есть задача #239 по упрощению развертывания контейнера "для себя", без traefik.

**Comment by Astromis** [comment]
Спасибо большое. Для тех, кто как я не очень силен в докере (и чтобы никто не сидел час потому что спутал порядок портов в port mapping) выложу конфиг для развертывания на 5000 порте.
<details><summary>docker-compose.yaml</summary>
<p>

```yaml
version: "3.3"
services:
  bonsai:
    image: impworks/bonsai:latest
    restart: unless-stopped
    volumes:
      - images:/app/wwwroot/media
    environment:
      - ConnectionStrings__Database=Server=postgres;Port=5432;Database=bonsai;User Id=bonsai;Password=test;Persist Security Info=true
      - Auth__AllowPasswordAuth=true
      - WebServer__RequireHttps=false
      - Debug__DetailedExceptions=false
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5000:80
    stop_signal: SIGKILL
    links:
      - postgres

  postgres:
    image: postgres:12.4
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: bonsai
      POSTGRES_DB: bonsai

volumes:
  database: {}
  images: {}
```

</p>
</details> 

@impworks, разрешите еще один вопрос задам. А можно как-то изменить рутовый путь (вместо `/` сделать, например, `/bonsai`) без изменения в коде? Мне это нужно, чтобы через nginx все красиво сделать.
